[tool.pytest.ini_options]
minversion = "6.0"
python_classes = ""
python_functions = ""
testpaths = ["src/soc"]
required_plugins = ["pytest-xdist>=1.0.0", "pytest-output-to-files>=0.1.0"]
addopts = [
    "-n",
    "auto",
    "--shorten-output-dir=test-out",
]
