name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    # Run everyday at 3 AM UTC on Sunday
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    permissions:
      contents: write
    steps:
      - name: mirror
        id: mirror
        uses: Libre-SOC-mirrors/github-mirror-action@main
        with:
          origin: 'https://git.libre-soc.org/git/soc.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
